import type { LayoutConfig } from "../types/layout"

export const layoutConfigs: LayoutConfig[] = [
  {
    id: "whatsapp",
    name: "WhatsApp",
    bubbleStyle: "rounded",
    headerStyle: "full",
    fonts: {
      header: "-apple-system, \"SF Pro Text\", \"Helvetica Neue\", Arial, sans-serif",
      body: "-apple-system, \"SF Pro Text\", \"Helvetica Neue\", Arial, sans-serif",
    },
    radius: "1.25rem",
    showAvatars: true,
    showStatus: true,
    themes: [
      {
        id: "light",
        name: "Light",
        colors: {
          background: "#ece5dd",
          surface: "#f0f2f5",
          header: "#075e54",
          headerText: "#f6f7f7",
          bubbleSent: "#dcf8c6",
          bubbleSentText: "#111b21",
          bubbleReceived: "#ffffff",
          bubbleReceivedText: "#111b21",
          input: "#ffffff",
          inputText: "#111b21",
          accent: "#25d366",
          muted: "#667781",
          border: "#d1d7db",
        },
        pattern: "url('/assets/whatsapp-light.webp')",
      },
      {
        id: "dark",
        name: "Dark",
        colors: {
          background: "#0b141a",
          surface: "#202c33",
          header: "#202c33",
          headerText: "#e9edef",
          bubbleSent: "#005c4b",
          bubbleSentText: "#e9edef",
          bubbleReceived: "#202c33",
          bubbleReceivedText: "#e9edef",
          input: "#2a3942",
          inputText: "#e9edef",
          accent: "#00a884",
          muted: "#8696a0",
          border: "#2a3942",
        },
        pattern: "url('/assets/whatsapp-dark.webp')",
      },
    ],
  },
  {
    id: "imessage",
    name: "iMessage",
    bubbleStyle: "rounded",
    headerStyle: "compact",
    fonts: {
      header: "-apple-system, \"SF Pro Text\", \"Helvetica Neue\", Arial, sans-serif",
      body: "-apple-system, \"SF Pro Text\", \"Helvetica Neue\", Arial, sans-serif",
    },
    radius: "1.5rem",
    showAvatars: false,
    showStatus: false,
    themes: [
      {
        id: "light",
        name: "Light",
        colors: {
          background: "#f2f2f7",
          surface: "#ffffff",
          header: "#f7f7f7",
          headerText: "#000000",
          bubbleSent: "#0a84ff",
          bubbleSentText: "#ffffff",
          bubbleReceived: "#e5e5ea",
          bubbleReceivedText: "#000000",
          input: "#ffffff",
          inputText: "#000000",
          accent: "#0a84ff",
          muted: "#8e8e93",
          border: "#d1d1d6",
        },
        pattern:
          "radial-gradient(circle at 1px 1px, rgba(0,0,0,0.06) 1px, transparent 0)",
      },
      {
        id: "dark",
        name: "Dark",
        colors: {
          background: "#000000",
          surface: "#1c1c1e",
          header: "#1c1c1e",
          headerText: "#f2f2f7",
          bubbleSent: "#0a84ff",
          bubbleSentText: "#ffffff",
          bubbleReceived: "#2c2c2e",
          bubbleReceivedText: "#f2f2f7",
          input: "#1c1c1e",
          inputText: "#f2f2f7",
          accent: "#0a84ff",
          muted: "#8e8e93",
          border: "#2c2c2e",
        },
        pattern:
          "radial-gradient(circle at 1px 1px, rgba(255,255,255,0.05) 1px, transparent 0)",
      },
    ],
  },
  {
    id: "snapchat",
    name: "Snapchat",
    bubbleStyle: "rounded",
    headerStyle: "compact",
    fonts: {
      header: "\"Avenir Next\", \"Helvetica Neue\", Arial, sans-serif",
      body: "\"Avenir Next\", \"Helvetica Neue\", Arial, sans-serif",
    },
    radius: "1.25rem",
    showAvatars: false,
    showStatus: false,
    themes: [
      {
        id: "light",
        name: "Light",
        colors: {
          background: "#ffffff",
          surface: "#ffffff",
          header: "#ffffff",
          headerText: "#0b0b0c",
          bubbleSent: "#1c89ff",
          bubbleSentText: "#ffffff",
          bubbleReceived: "#ff3b6d",
          bubbleReceivedText: "#0b0b0c",
          input: "#f1f2f4",
          inputText: "#0b0b0c",
          accent: "#fffc00",
          muted: "#8e8e93",
          border: "#e6e7ea",
        },
      },
      {
        id: "dark",
        name: "Dark",
        colors: {
          background: "#0b0b0c",
          surface: "#0f0f10",
          header: "#0f0f10",
          headerText: "#f5f5f7",
          bubbleSent: "#1c89ff",
          bubbleSentText: "#ffffff",
          bubbleReceived: "#ff3b6d",
          bubbleReceivedText: "#f5f5f7",
          input: "#1a1a1c",
          inputText: "#f5f5f7",
          accent: "#fffc00",
          muted: "#9aa0a6",
          border: "#1f1f22",
        },
      },
    ],
  },
  {
    id: "messenger",
    name: "Messenger",
    bubbleStyle: "rounded",
    headerStyle: "full",
    fonts: {
      header: "\"Helvetica Neue\", Arial, sans-serif",
      body: "\"Helvetica Neue\", Arial, sans-serif",
    },
    radius: "1.25rem",
    showAvatars: false,
    showStatus: false,
    themes: [
      {
        id: "light",
        name: "Light",
        colors: {
          background: "#ffffff",
          surface: "#ffffff",
          header: "#ffffff",
          headerText: "#050505",
          bubbleSent: "#0084ff",
          bubbleSentText: "#ffffff",
          bubbleReceived: "#e4e6eb",
          bubbleReceivedText: "#050505",
          input: "#ffffff",
          inputText: "#050505",
          accent: "#0084ff",
          muted: "#8a8d91",
          border: "#e4e6eb",
        },
      },
      {
        id: "dark",
        name: "Dark",
        colors: {
          background: "#0b0b0c",
          surface: "#1c1e21",
          header: "#1c1e21",
          headerText: "#e4e6eb",
          bubbleSent: "#0084ff",
          bubbleSentText: "#ffffff",
          bubbleReceived: "#3a3b3c",
          bubbleReceivedText: "#e4e6eb",
          input: "#1c1e21",
          inputText: "#e4e6eb",
          accent: "#0084ff",
          muted: "#b0b3b8",
          border: "#2f3031",
        },
      },
    ],
  },
]

export const defaultLayoutId = layoutConfigs[0].id

export const getLayoutConfig = (id: LayoutConfig["id"]) =>
  layoutConfigs.find((layout) => layout.id === id) ?? layoutConfigs[0]
