import type { LayoutConfig, LayoutType } from '../types/layout';

export const AVAILABLE_LAYOUTS: LayoutConfig[] = [
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    description: 'WhatsApp-style chat interface',
    bubbleStyle: 'rounded-tail',
    headerStyle: 'full',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Helvetica, sans-serif',
    lightColors: {
      background: '#ECE5DD',
      chatBackground: '#E5DDD5',
      sentBubble: '#D9FDD3',
      receivedBubble: '#FFFFFF',
      sentText: '#000000',
      receivedText: '#000000',
      timestamp: '#667781',
      primary: '#25D366',
      secondary: '#128C7E',
      border: '#D1D7DB',
      headerBackground: '#008069',
      headerText: '#FFFFFF',
      inputBackground: '#FFFFFF',
      inputText: '#000000',
      inputBorder: '#D1D7DB',
    },
    darkColors: {
      background: '#0B141A',
      chatBackground: '#0D1418',
      sentBubble: '#005C4B',
      receivedBubble: '#1F2C34',
      sentText: '#E9EDEF',
      receivedText: '#E9EDEF',
      timestamp: '#667781',
      primary: '#00A884',
      secondary: '#008069',
      border: '#2A3942',
      headerBackground: '#202C33',
      headerText: '#E9EDEF',
      inputBackground: '#202C33',
      inputText: '#E9EDEF',
      inputBorder: '#2A3942',
    },
    bubbleMaxWidth: '65%',
    bubblePadding: '6px 7px 8px 9px',
    bubbleMargin: '4px',
    borderRadius: '7.5px',
    supportsReactions: true,
    supportsReplies: true,
    supportsReadReceipts: true,
    supportsTypingIndicator: true,
  },
  {
    id: 'imessage',
    name: 'iMessage',
    description: 'Apple iMessage-style interface',
    bubbleStyle: 'rounded-tail',
    headerStyle: 'compact',
    fontFamily: '-apple-system, BlinkMacSystemFont, "San Francisco", "Helvetica Neue", sans-serif',
    lightColors: {
      background: '#FFFFFF',
      chatBackground: '#FFFFFF',
      sentBubble: '#007AFF',
      receivedBubble: '#E5E5EA',
      sentText: '#FFFFFF',
      receivedText: '#000000',
      timestamp: '#8E8E93',
      primary: '#007AFF',
      secondary: '#5AC8FA',
      border: '#C6C6C8',
      headerBackground: '#F6F6F6',
      headerText: '#000000',
      inputBackground: '#FFFFFF',
      inputText: '#000000',
      inputBorder: '#C6C6C8',
    },
    darkColors: {
      background: '#000000',
      chatBackground: '#000000',
      sentBubble: '#0A84FF',
      receivedBubble: '#3A3A3C',
      sentText: '#FFFFFF',
      receivedText: '#FFFFFF',
      timestamp: '#8E8E93',
      primary: '#0A84FF',
      secondary: '#64D2FF',
      border: '#3A3A3C',
      headerBackground: '#1C1C1E',
      headerText: '#FFFFFF',
      inputBackground: '#1C1C1E',
      inputText: '#FFFFFF',
      inputBorder: '#3A3A3C',
    },
    bubbleMaxWidth: '70%',
    bubblePadding: '8px 16px',
    bubbleMargin: '2px',
    borderRadius: '18px',
    supportsReactions: true,
    supportsReplies: true,
    supportsReadReceipts: true,
    supportsTypingIndicator: true,
  },
  {
    id: 'messenger',
    name: 'Messenger',
    description: 'Facebook Messenger-style interface',
    bubbleStyle: 'rounded',
    headerStyle: 'full',
    fontFamily: 'system-ui, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif',
    lightColors: {
      background: '#FFFFFF',
      chatBackground: '#FFFFFF',
      sentBubble: '#0084FF',
      receivedBubble: '#E4E6EB',
      sentText: '#FFFFFF',
      receivedText: '#000000',
      timestamp: '#65676B',
      primary: '#0084FF',
      secondary: '#00A2FF',
      border: '#CED0D4',
      headerBackground: '#FFFFFF',
      headerText: '#050505',
      inputBackground: '#F0F2F5',
      inputText: '#050505',
      inputBorder: '#CED0D4',
    },
    darkColors: {
      background: '#18191A',
      chatBackground: '#18191A',
      sentBubble: '#0084FF',
      receivedBubble: '#3A3B3C',
      sentText: '#FFFFFF',
      receivedText: '#E4E6EB',
      timestamp: '#B0B3B8',
      primary: '#0084FF',
      secondary: '#00A2FF',
      border: '#3E4042',
      headerBackground: '#242526',
      headerText: '#E4E6EB',
      inputBackground: '#3A3B3C',
      inputText: '#E4E6EB',
      inputBorder: '#3E4042',
    },
    bubbleMaxWidth: '60%',
    bubblePadding: '8px 12px',
    bubbleMargin: '2px',
    borderRadius: '18px',
    supportsReactions: true,
    supportsReplies: true,
    supportsReadReceipts: true,
    supportsTypingIndicator: true,
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Telegram-style interface',
    bubbleStyle: 'rounded',
    headerStyle: 'full',
    fontFamily: 'Roboto, "Helvetica Neue", sans-serif',
    lightColors: {
      background: '#FFFFFF',
      chatBackground: '#FFFFFF',
      sentBubble: '#EFFDDE',
      receivedBubble: '#FFFFFF',
      sentText: '#000000',
      receivedText: '#000000',
      timestamp: '#70B767',
      primary: '#0088CC',
      secondary: '#64B5F6',
      border: '#DADCE0',
      headerBackground: '#517DA2',
      headerText: '#FFFFFF',
      inputBackground: '#FFFFFF',
      inputText: '#000000',
      inputBorder: '#DADCE0',
    },
    darkColors: {
      background: '#17212B',
      chatBackground: '#0E1621',
      sentBubble: '#2B5278',
      receivedBubble: '#182533',
      sentText: '#FFFFFF',
      receivedText: '#FFFFFF',
      timestamp: '#5288C1',
      primary: '#0088CC',
      secondary: '#64B5F6',
      border: '#0E1621',
      headerBackground: '#17212B',
      headerText: '#FFFFFF',
      inputBackground: '#17212B',
      inputText: '#FFFFFF',
      inputBorder: '#0E1621',
    },
    bubbleMaxWidth: '70%',
    bubblePadding: '6px 12px 8px',
    bubbleMargin: '4px',
    borderRadius: '12px',
    supportsReactions: true,
    supportsReplies: true,
    supportsReadReceipts: true,
    supportsTypingIndicator: true,
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Discord-style interface',
    bubbleStyle: 'minimal',
    headerStyle: 'full',
    fontFamily: '"gg sans", "Noto Sans", "Helvetica Neue", Helvetica, Arial, sans-serif',
    lightColors: {
      background: '#FFFFFF',
      chatBackground: '#FFFFFF',
      sentBubble: 'transparent',
      receivedBubble: 'transparent',
      sentText: '#313338',
      receivedText: '#313338',
      timestamp: '#949BA4',
      primary: '#5865F2',
      secondary: '#949BA4',
      border: '#E3E5E8',
      headerBackground: '#F2F3F5',
      headerText: '#313338',
      inputBackground: '#EBEDEF',
      inputText: '#313338',
      inputBorder: '#E3E5E8',
    },
    darkColors: {
      background: '#313338',
      chatBackground: '#313338',
      sentBubble: 'transparent',
      receivedBubble: 'transparent',
      sentText: '#DBDEE1',
      receivedText: '#DBDEE1',
      timestamp: '#949BA4',
      primary: '#5865F2',
      secondary: '#949BA4',
      border: '#26282C',
      headerBackground: '#2B2D31',
      headerText: '#F2F3F5',
      inputBackground: '#383A40',
      inputText: '#DBDEE1',
      inputBorder: '#26282C',
    },
    bubbleMaxWidth: '100%',
    bubblePadding: '2px 48px 2px 72px',
    bubbleMargin: '0',
    borderRadius: '0',
    supportsReactions: true,
    supportsReplies: true,
    supportsReadReceipts: false,
    supportsTypingIndicator: true,
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Slack-style interface',
    bubbleStyle: 'minimal',
    headerStyle: 'full',
    fontFamily: '"Slack-Lato", Lato, appleLogo, sans-serif',
    lightColors: {
      background: '#FFFFFF',
      chatBackground: '#FFFFFF',
      sentBubble: 'transparent',
      receivedBubble: 'transparent',
      sentText: '#1D1C1D',
      receivedText: '#1D1C1D',
      timestamp: '#616061',
      primary: '#611F69',
      secondary: '#1264A3',
      border: '#DDDDDD',
      headerBackground: '#FFFFFF',
      headerText: '#1D1C1D',
      inputBackground: '#FFFFFF',
      inputText: '#1D1C1D',
      inputBorder: '#DDDDDD',
    },
    darkColors: {
      background: '#1A1D21',
      chatBackground: '#1A1D21',
      sentBubble: 'transparent',
      receivedBubble: 'transparent',
      sentText: '#D1D2D3',
      receivedText: '#D1D2D3',
      timestamp: '#ABABAD',
      primary: '#611F69',
      secondary: '#1264A3',
      border: '#474A4D',
      headerBackground: '#1A1D21',
      headerText: '#D1D2D3',
      inputBackground: '#1A1D21',
      inputText: '#D1D2D3',
      inputBorder: '#474A4D',
    },
    bubbleMaxWidth: '100%',
    bubblePadding: '8px 20px 8px 48px',
    bubbleMargin: '0',
    borderRadius: '0',
    supportsReactions: true,
    supportsReplies: true,
    supportsReadReceipts: false,
    supportsTypingIndicator: true,
  },
];

export const DEFAULT_LAYOUT: LayoutType = 'whatsapp';